### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ctbeiser** [h3poteto/Whalebird#107]
I've been planning to build a niche twitter client, and this looks like a great codebase to start with; is Whalebird licensed under a free license? (MIT, etc)

**Comment by h3poteto** [comment]
I didn't write the license, but I will make this a MIT License. I will write a license.

There is one problem in your development. When call API server in Whalebird, I set secret token. And I don't commit that secret token generator.
So, I will write how to build this app on your machine in README after write a license.

**Comment by h3poteto** [comment]
I've added a license.
