### ISSUE TITLE
Hi. Can this application also be translated into English?

### ISSUE THREAD

**Issue by ghost** [h3poteto/Whalebird#85]
Can xcode do that for you?

It looks cool and I want to buy it

However, I do not know how to speak Japanese, so it may be difficult to use.

Sorry if the translation sounds bad. I used Google and Bing.

んにちは。 このアプリケーションを英語にも翻訳できますか？ 

xcodeはそれをあなたのためにすることができますか？

それはクールに見え、私はそれを購入したい。

しかし、私は日本語を話す方法がわからないので、使いにくいかもしれません。

翻訳が悪い場合は申し訳ありません。 私はGoogleとBingを使いました。

**Comment by h3poteto** [comment]
Thank you for your question, and writing Japanese!!
It's okay to write in English.

I understand your request.
I will translate this application in English. Please wait a little more.

Sorry, I never thought many people buy Whalebird, so I developed in Japanese. 
But, that judgment was not good.

I will create Localizable files, and upload to AppStore for the whole world.

**Comment by ghost** [comment]
Thank you.

**Comment by h3poteto** [comment]
@laserstrike Sorry for the delay, I release new version today.
I translate this application in English, so the latest version display in English, maybe.

Thanks.

**Comment by ghost** [comment]
Yes! Thank you so much. I already bought the app. 
The only word with a mistake I found is where it says "updat"; I think it should be "update".

![2017-01-10 15 28 21](https://cloud.githubusercontent.com/assets/13025358/21823896/0b0061ec-d74b-11e6-8414-31d1e499d20b.png)

Thanks again.

**Comment by h3poteto** [comment]
Oh...sorry.
I will fix this typo in next version.

Thank you.
