### ISSUE TITLE
Remove the blue header that shows up when refreshing tweets

### ISSUE THREAD

**Issue by ghost** [h3poteto/Whalebird#96]
Consider removing the blue header that shows up when using pull to refresh on timeline. It's probably unnecessary.

**Comment by h3poteto** [comment]
I like the header because I want to know about update result. Why do you think it is unnecessary?

**Comment by ghost** [comment]
I'm sorry, but I no longer have an iPhone. So you can close the issues that you find inconvenient. Thank you.

**Comment by h3poteto** [comment]
Oh...
